name: Build Electron App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux:
    strategy: 
      matrix:
       os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    environment: build

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            flatpak \
            flatpak-builder \
            elfutils
          flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo 
          flatpak install --user -y flathub \
            org.freedesktop.Platform//25.08 \
            org.freedesktop.Sdk//25.08 \
            org.electronjs.Electron2.BaseApp//25.08

      - name: Install dependencies
        run: npm ci --save-dev

      - name: Make Linux distributables
        run: npm run make

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v6
        with:
          name: linux-artifacts
          path: out/make/**
          
      - name: Publish as draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish

  build-windows:
    strategy: 
      matrix:
        # os: [ windows-latest, windows-11-arm ]
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}

    environment: build

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --save-dev

      - name: Make Windows distributables
        run: npm run make

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v6
        with:
          name: windows-artifacts
          path: out/make/**
      
      - name: Publish as draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish